version: '3'

services:
  db:
    image: mongo:latest
    restart: on-failure
    container_name: portais-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  portais:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # YOUR_ENV: production
        YOUR_ENV: development
    env_file: .env
    volumes:
      - $PWD/portais_tech:/portais_tech
    depends_on:
      - db
