version: '3'

services:
  db:
    image: mongo:latest
    restart: on-failure
    container_name: portais-mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    command: mongod
  portais:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD/portais_tech:/portais_tech
    environment:
      - YOUR_ENV=production
      # - YOUR_ENV=development
    depends_on:
      - db
