version: '3'

services:
  db:
    image: mongo:latest
    restart: on-failure
    container_name: portais-mongodb
    ports:
      - 27017:27017
  portais:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # YOUR_ENV: production
        YOUR_ENV: development
    environment:
      # Ative para persistir os dados em json
      - USE_JSON=1  # 0 para False e 1 para True
      # Ative para persistir os dados em um mongodb
      - USE_MONGO=1
    volumes:
      - $PWD/portais_tech:/portais_tech
    depends_on:
      - db
